// Generated by scripts/generate-twitchat-protocol.mjs from https://raw.githubusercontent.com/Durss/Twitchat/main/src_front/events/TwitchatEvent.ts
// and https://raw.githubusercontent.com/Durss/Twitchat/main/PUBLIC_API.md
// Don't edit by hand: rerun `npm run generate:twitchat-protocol` instead.
// IDE typings of static/js/twitchat.js; never served.

/** Every action Twitchat accepts. */
type TwitchatActionType = 
    | "GREET_FEED_READ"
    | "GREET_FEED_READ_ALL"
    | "CHAT_FEED_READ"
    | "CHAT_FEED_READ_ALL"
    | "CHAT_FEED_PAUSE"
    | "CHAT_FEED_UNPAUSE"
    | "CHAT_FEED_SCROLL_UP"
    | "CHAT_FEED_SCROLL_DOWN"
    | "CHAT_FEED_SCROLL"
    | "CHAT_FEED_SCROLL_BOTTOM"
    | "CHAT_FEED_SELECT"
    | "CHAT_FEED_SELECT_ACTION_CANCEL"
    | "CHAT_FEED_SELECT_ACTION_DELETE"
    | "CHAT_FEED_SELECT_ACTION_BAN"
    | "CHAT_FEED_SELECT_CHOOSING_ACTION"
    | "CHAT_FEED_SELECT_ACTION_PIN"
    | "CHAT_FEED_SELECT_ACTION_HIGHLIGHT"
    | "CHAT_FEED_SELECT_ACTION_SHOUTOUT"
    | "CLEAR_CHAT_HIGHLIGHT"
    | "MERGE_TOGGLE"
    | "POLL_TOGGLE"
    | "POLL_CREATE"
    | "PREDICTION_TOGGLE"
    | "BINGO_TOGGLE"
    | "RAFFLE_TOGGLE"
    | "VIEWERS_COUNT_TOGGLE"
    | "MOD_TOOLS_TOGGLE"
    | "CENSOR_DELETED_MESSAGES_TOGGLE"
    | "GET_CURRENT_TRACK"
    | "GET_WHEEL_OVERLAY_PRESENCE"
    | "GET_BITSWALL_OVERLAY_PRESENCE"
    | "GET_CREDITS_OVERLAY_PRESENCE"
    | "WHEEL_OVERLAY_START"
    | "GET_CURRENT_TIMERS"
    | "GET_TIMER_OVERLAY_PRESENCE"
    | "SET_EMERGENCY_MODE"
    | "GET_CHAT_HIGHLIGHT_OVERLAY_PRESENCE"
    | "SET_CHAT_HIGHLIGHT_OVERLAY_MESSAGE"
    | "SHOW_CLIP"
    | "START_EMERGENCY"
    | "STOP_EMERGENCY"
    | "SHOUTOUT"
    | "STOP_TTS"
    | "ENABLE_STT"
    | "DISABLE_STT"
    | "RAFFLE_START"
    | "RAFFLE_PICK_WINNER"
    | "RAFFLE_END"
    | "GET_COLS_COUNT"
    | "COUNTER_GET_ALL"
    | "TRIGGERS_GET_ALL"
    | "EXECUTE_TRIGGER"
    | "TOGGLE_TRIGGER"
    | "SEND_MESSAGE"
    | "COUNTER_GET"
    | "COUNTER_ADD"
    | "TIMER_ADD"
    | "COUNTDOWN_ADD"
    | "CREATE_POLL"
    | "STOP_POLL"
    | "CREATE_PREDICTION"
    | "STOP_PREDICTION"
    | "CREATE_RAFFLE"
    | "STOP_RAFFLE"
    | "GET_SUMMARY_DATA"
    | "GET_AD_BREAK_OVERLAY_PRESENCE"
    | "GET_AD_BREAK_OVERLAY_PARAMETERS"
    | "GET_DISTORT_OVERLAY_PARAMETERS"
    | "GET_BITS_WALL_OVERLAY_PARAMETERS"
    | "CUSTOM_CHAT_MESSAGE"
    | "GET_PREDICTIONS_OVERLAY_PRESENCE"
    | "GET_PREDICTIONS_OVERLAY_PARAMETERS"
    | "GET_POLLS_OVERLAY_PRESENCE"
    | "GET_CHAT_POLL_OVERLAY_PRESENCE"
    | "GET_POLLS_OVERLAY_PARAMETERS"
    | "GET_CHAT_POLL_OVERLAY_PARAMETERS"
    | "GET_BINGO_GRID_PARAMETERS"
    | "GET_LABEL_OVERLAY_PARAMS"
    | "GET_LABEL_OVERLAY_PLACEHOLDERS"
    | "AUTOMOD_ACCEPT"
    | "AUTOMOD_REJECT"
    | "GET_DONATION_GOALS_OVERLAY_PARAMS"
    | "QNA_HIGHLIGHT"
    | "QNA_SKIP"
    | "QNA_SESSION_GET_ALL"
    | "HIDE_ALERT"
    | "GET_ANIMATED_TEXT_CONFIGS"
    | "ANIMATED_TEXT_SET"
    | "ANIMATED_TEXT_CLOSE"
    | "GET_CUSTOM_TRAIN_STATE"
    | "PLAY_SFXR";

/** Every event Twitchat sends. */
type TwitchatEventType = 
    | "TWITCHAT_READY"
    | "OBS_WEBSOCKET_CONNECTED"
    | "OBS_WEBSOCKET_DISCONNECTED"
    | "TEXT_UPDATE"
    | "ACTION_BATCH"
    | "SPEECH_END"
    | "REMOTE_TEMP_TEXT_EVENT"
    | "REMOTE_FINAL_TEXT_EVENT"
    | "MESSAGE_READ"
    | "MESSAGE_NON_FOLLOWER"
    | "MESSAGE_FILTERED"
    | "MESSAGE_DELETED"
    | "MESSAGE_FIRST"
    | "MESSAGE_FIRST_ALL_TIME"
    | "MESSAGE_WHISPER"
    | "FOLLOW"
    | "REWARD_REDEEM"
    | "BITS"
    | "SUBSCRIPTION"
    | "MENTION"
    | "CURRENT_TRACK"
    | "TRACK_ADDED_TO_QUEUE"
    | "WHEEL_OVERLAY_PRESENCE"
    | "BITSWALL_OVERLAY_PRESENCE"
    | "CREDITS_OVERLAY_PRESENCE"
    | "COUNTDOWN_START"
    | "COUNTDOWN_COMPLETE"
    | "TIMER_START"
    | "TIMER_STOP"
    | "TIMER_OVERLAY_PRESENCE"
    | "POLL_PROGRESS"
    | "CHAT_POLL_PROGRESS"
    | "PREDICTION_PROGRESS"
    | "RAFFLE_RESULT"
    | "EMERGENCY_MODE"
    | "CHAT_HIGHLIGHT_OVERLAY_PRESENCE"
    | "CHAT_HIGHLIGHT_OVERLAY_CONFIRM"
    | "VOICEMOD_CHANGE"
    | "SET_COLS_COUNT"
    | "COUNTER_UPDATE"
    | "COUNTER_LIST"
    | "TRIGGER_LIST"
    | "OBS_SCENE_CHANGE"
    | "OBS_SOURCE_TOGGLE"
    | "OBS_MUTE_TOGGLE"
    | "OBS_FILTER_TOGGLE"
    | "OBS_STREAM_STATE"
    | "OBS_RECORD_STATE"
    | "OBS_PLAYBACK_ENDED"
    | "OBS_PLAYBACK_STARTED"
    | "OBS_PLAYBACK_PAUSED"
    | "OBS_PLAYBACK_RESTARTED"
    | "OBS_PLAYBACK_NEXT"
    | "OBS_PLAYBACK_PREVIOUS"
    | "OBS_INPUT_NAME_CHANGED"
    | "OBS_SCENE_NAME_CHANGED"
    | "OBS_FILTER_NAME_CHANGED"
    | "MUSIC_PLAYER_HEAT_CLICK"
    | "LABELS_UPDATE"
    | "SUMMARY_DATA"
    | "ENDING_CREDITS_CONFIGS"
    | "ENDING_CREDITS_CONTROL"
    | "ENDING_CREDITS_COMPLETE"
    | "AD_BREAK_OVERLAY_PRESENCE"
    | "AD_BREAK_OVERLAY_PARAMETERS"
    | "AD_BREAK_DATA"
    | "DISTORT_OVERLAY_PARAMETERS"
    | "BITSWALL_OVERLAY_PARAMETERS"
    | "PREDICTIONS_OVERLAY_PRESENCE"
    | "PREDICTIONS_OVERLAY_PARAMETERS"
    | "POLLS_OVERLAY_PRESENCE"
    | "CHAT_POLL_OVERLAY_PRESENCE"
    | "POLLS_OVERLAY_PARAMETERS"
    | "CHAT_POLL_OVERLAY_PARAMETERS"
    | "BINGO_GRID_PARAMETERS"
    | "BINGO_GRID_OVERLAY_PRESENCE"
    | "BINGO_GRID_HEAT_CLICK"
    | "BINGO_GRID_OVERLAY_VIEWER_EVENT"
    | "BINGO_GRID_OVERLAY_LEADER_BOARD"
    | "LABEL_OVERLAY_PARAMS"
    | "LABEL_OVERLAY_PLACEHOLDERS"
    | "DONATION_GOALS_OVERLAY_PARAMS"
    | "DONATION_EVENT"
    | "QNA_SESSION_LIST"
    | "ANIMATED_TEXT_CONFIGS"
    | "ANIMATED_TEXT_SHOW_COMPLETE"
    | "ANIMATED_TEXT_HIDE_COMPLETE"
    | "CUSTOM_TRAIN_STATE"
    | "CHAT_HIGHLIGHT_OVERLAY_CLOSE";

/** Every event Twitchat sends, documented when PUBLIC_API.md does. */
interface TwitchatEventMap {
    TWITCHAT_READY: Record<string, any>;
    OBS_WEBSOCKET_CONNECTED: Record<string, any>;
    OBS_WEBSOCKET_DISCONNECTED: Record<string, any>;
    TEXT_UPDATE: Record<string, any>;
    ACTION_BATCH: Record<string, any>;
    SPEECH_END: Record<string, any>;
    REMOTE_TEMP_TEXT_EVENT: Record<string, any>;
    REMOTE_FINAL_TEXT_EVENT: Record<string, any>;
    /**
     * Sent when clicking a message on the chat to mark it as read.
     * Only sent for users' messages and whispers.
     * Poll results, sub/bits/.. alerts, notices, etc... won't fire this event
     *
     * Data:
     * ```ts
     * {
     *     channel:string,
     *     message:string,
     * }
     * ```
     */
    MESSAGE_READ: Record<string, any>;
    /**
     * Sent when a non-follower sends a message
     *
     * Data:
     * ```ts
     * {
     *     channel:string,
     *     message:string,
     *     user: {
     *         id:string,
     *         login:string,
     *         displayName:string,
     *     }
     * }
     * ```
     */
    MESSAGE_NON_FOLLOWER: Record<string, any>;
    MESSAGE_FILTERED: Record<string, any>;
    /**
     * Sent when a message is deleted.
     *
     * Data:
     * ```ts
     * {
     *     channel:string,
     *     message:string,
     *     user: {
     *         id:string,
     *         login:string,
     *         displayName:string,
     *     }
     * }
     * ```
     */
    MESSAGE_DELETED: Record<string, any>;
    /**
     * Sent when a user sends their first message of the stream *("Greet them" section)*.
     *
     * Data:
     * ```ts
     * {
     *     channel:string,
     *     message:string,
     *     tags:any,//IRC tags data
     * }
     * ```
     */
    MESSAGE_FIRST: Record<string, any>;
    /**
     * Sent when a user sends their first message on the channel.
     *
     * Data:
     * ```ts
     * {
     *     channel:string,
     *     message:string,
     *     tags:any,//IRC tags data
     * }
     * ```
     */
    MESSAGE_FIRST_ALL_TIME: Record<string, any>;
    /**
     * The actual message received isn't sent for privacy reasons.
     *
     * Data:
     * ```ts
     * {
     *     unreadCount:number,//Number of unread whispers
     *     user:{
     *         id: string,
     *         login: string,
     *         displayName: string,
     *     },
     * }
     * ```
     */
    MESSAGE_WHISPER: Record<string, any>;
    /**
     * Sent when a user follows the channel
     *
     * Data:
     * ```ts
     * {
     *     user: {
     *         id: string,
     *         login: string,
     *         displayName: string,
     *     }
     * }
     * ```
     */
    FOLLOW: Record<string, any>;
    REWARD_REDEEM: Record<string, any>;
    BITS: Record<string, any>;
    SUBSCRIPTION: Record<string, any>;
    /**
     * Called when a message contains a mention of your nickname
     *
     * Data:
     * ```ts
     * {
     *     display_name: string,
     *     username: string,
     *     user_id: string,
     * }
     * ```
     */
    MENTION: Record<string, any>;
    /**
     * Sent when a new track is playing on spotify or when playback is stopped
     *
     * Data:
     * ```ts
     * {
     *     trackName:string,
     *     artistName:string,
     *     trackDuration:number,
     *     trackPlaybackPos:number,
     *     cover:string,
     * }
     * ```
     */
    CURRENT_TRACK: Record<string, any>;
    /**
     * Sent when a new track is added to the queue
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     title:string,
     *     artist:string,
     *     album:string,
     *     cover:string,
     *     duration:number,
     *     url:string,
     * }
     * ```
     */
    TRACK_ADDED_TO_QUEUE: Record<string, any>;
    /**
     * Sent when a wheel overlay advertises its presence
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     */
    WHEEL_OVERLAY_PRESENCE: Record<string, any>;
    BITSWALL_OVERLAY_PRESENCE: Record<string, any>;
    CREDITS_OVERLAY_PRESENCE: Record<string, any>;
    /**
     * Sent when a countdown start
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     startAt:string,//formatted date
     *     startAt_ms:number,//Timestamp in ms
     *     duration:number,//Duration formatted
     *     duration_ms:number,//Duration in ms
     * }
     * ```
     */
    COUNTDOWN_START: Record<string, any>;
    /**
     * Sent when a countdown completes
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     startAt:string,//formatted date
     *     startAt_ms:number,//Timestamp in ms
     *     endAt:string,//formatted date
     *     endAt_ms:number,//Timestamp in ms
     *     duration:number,//Duration formatted
     *     duration_ms:number,//Duration in ms
     * }
     * ```
     */
    COUNTDOWN_COMPLETE: Record<string, any>;
    /**
     * Sent when a timer is started
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     startAt:number,//Timestamp in ms
     * }
     * ```
     */
    TIMER_START: Record<string, any>;
    /**
     * Sent when stoping a timer
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     startAt:number,//Timestamp in ms
     *     stopAt:number,//Timestamp in ms
     * }
     * ```
     */
    TIMER_STOP: Record<string, any>;
    /**
     * Sent when a timer overlay advertises its presence
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     */
    TIMER_OVERLAY_PRESENCE: Record<string, any>;
    /**
     * Sent when a poll starts, updates (when someone votes) and ends.
     *
     * Data:
     * ```ts
     * {
     *     channel_id: string;
     *     id: string,
     *     duration_s: number,
     *     started_at: number,
     *     ended_at?: number,
     *     choices: {
     *         id: string,
     *         label: string,
     *         votes: number,
     *     }[],
     *     winner?:{
     *         id: string,
     *         label: string,
     *         votes: number,
     *     },
     * };
     * ```
     */
    POLL_PROGRESS: Record<string, any>;
    CHAT_POLL_PROGRESS: Record<string, any>;
    /**
     * Sent when a prediction starts, updates (when someone votes) and ends.
     *
     * Data:
     * ```ts
     * {
     *     channel_id: string,
     *     title: string,
     *     duration_s: number,
     *     outcomes: {
     *         id: string;
     *         label: string;
     *         votes: number;
     *         voters: number;
     *     }[],
     *     pendingAnswer: boolean,
     *     started_at: number,
     *     ended_at?: number,
     *     winner?:{
     *         id: string;
     *         label: string;
     *         votes: number;
     *         voters: number;
     *     },
     * }
     * ```
     */
    PREDICTION_PROGRESS: Record<string, any>;
    /**
     * Sent when a raffle completes
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     winner:{
     *         label:string;
     *         id:string;//user ID in case of a chat raffle
     *         score:number;//Score value if using ponderation options
     *     },
     * }
     * ```
     */
    RAFFLE_RESULT: Record<string, any>;
    /**
     * Sent when the emergency mode is started or stopped
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     enabled:boolean
     * }
     * ```
     */
    EMERGENCY_MODE: Record<string, any>;
    /**
     * Sent when a chat highlight overlay advertises its presence
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     enabled:boolean
     * }
     * ```
     */
    CHAT_HIGHLIGHT_OVERLAY_PRESENCE: Record<string, any>;
    CHAT_HIGHLIGHT_OVERLAY_CONFIRM: Record<string, any>;
    /**
     * Sent when changing voicemod voice effect
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     voice:string
     * }
     * ```
     */
    VOICEMOD_CHANGE: Record<string, any>;
    SET_COLS_COUNT: Record<string, any>;
    COUNTER_UPDATE: Record<string, any>;
    COUNTER_LIST: Record<string, any>;
    TRIGGER_LIST: Record<string, any>;
    OBS_SCENE_CHANGE: Record<string, any>;
    OBS_SOURCE_TOGGLE: Record<string, any>;
    OBS_MUTE_TOGGLE: Record<string, any>;
    OBS_FILTER_TOGGLE: Record<string, any>;
    OBS_STREAM_STATE: Record<string, any>;
    OBS_RECORD_STATE: Record<string, any>;
    OBS_PLAYBACK_ENDED: Record<string, any>;
    OBS_PLAYBACK_STARTED: Record<string, any>;
    OBS_PLAYBACK_PAUSED: Record<string, any>;
    OBS_PLAYBACK_RESTARTED: Record<string, any>;
    OBS_PLAYBACK_NEXT: Record<string, any>;
    OBS_PLAYBACK_PREVIOUS: Record<string, any>;
    OBS_INPUT_NAME_CHANGED: Record<string, any>;
    OBS_SCENE_NAME_CHANGED: Record<string, any>;
    OBS_FILTER_NAME_CHANGED: Record<string, any>;
    MUSIC_PLAYER_HEAT_CLICK: Record<string, any>;
    LABELS_UPDATE: Record<string, any>;
    SUMMARY_DATA: Record<string, any>;
    ENDING_CREDITS_CONFIGS: Record<string, any>;
    ENDING_CREDITS_CONTROL: Record<string, any>;
    ENDING_CREDITS_COMPLETE: Record<string, any>;
    AD_BREAK_OVERLAY_PRESENCE: Record<string, any>;
    AD_BREAK_OVERLAY_PARAMETERS: Record<string, any>;
    AD_BREAK_DATA: Record<string, any>;
    DISTORT_OVERLAY_PARAMETERS: Record<string, any>;
    BITSWALL_OVERLAY_PARAMETERS: Record<string, any>;
    PREDICTIONS_OVERLAY_PRESENCE: Record<string, any>;
    PREDICTIONS_OVERLAY_PARAMETERS: Record<string, any>;
    POLLS_OVERLAY_PRESENCE: Record<string, any>;
    CHAT_POLL_OVERLAY_PRESENCE: Record<string, any>;
    POLLS_OVERLAY_PARAMETERS: Record<string, any>;
    CHAT_POLL_OVERLAY_PARAMETERS: Record<string, any>;
    BINGO_GRID_PARAMETERS: Record<string, any>;
    BINGO_GRID_OVERLAY_PRESENCE: Record<string, any>;
    BINGO_GRID_HEAT_CLICK: Record<string, any>;
    BINGO_GRID_OVERLAY_VIEWER_EVENT: Record<string, any>;
    BINGO_GRID_OVERLAY_LEADER_BOARD: Record<string, any>;
    LABEL_OVERLAY_PARAMS: Record<string, any>;
    LABEL_OVERLAY_PLACEHOLDERS: Record<string, any>;
    DONATION_GOALS_OVERLAY_PARAMS: Record<string, any>;
    DONATION_EVENT: Record<string, any>;
    QNA_SESSION_LIST: Record<string, any>;
    ANIMATED_TEXT_CONFIGS: Record<string, any>;
    ANIMATED_TEXT_SHOW_COMPLETE: Record<string, any>;
    ANIMATED_TEXT_HIDE_COMPLETE: Record<string, any>;
    CUSTOM_TRAIN_STATE: Record<string, any>;
    CHAT_HIGHLIGHT_OVERLAY_CLOSE: Record<string, any>;
}

/** A Twitchat message as carried by OBS's CustomEvent. */
interface TwitchatEnvelope {
    origin: "twitchat";
    /** Unique per message: lets every client drop the echoes of its own. */
    id?: string;
    type: TwitchatEventType | TwitchatActionType;
    data?: Record<string, any>;
}

interface TwitchatRequestOptions {
    /** How long to wait for the answer of a "get" action, in ms (3000 by default). */
    timeout?: number;
}

/** One shortcut per action, see CatapultTwitchat.actions. */
interface TwitchatActions {
    /**
     * Marks "`count`" messages as read in the "Greet them" section.
     * *Default value = 1*
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     "count": number,
     * }
     * ```
     *
     * Sends GREET_FEED_READ. Resolves once sent: Twitchat doesn't answer it.
     */
    greetFeedRead(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Marks all the messages as read in the "Greet them" section
     * ### JSON param
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends GREET_FEED_READ_ALL. Resolves once sent: Twitchat doesn't answer it.
     */
    greetFeedReadAll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Marks "`count`" messages as read in the chat feed.
     * `count` value can be negative to move the read mark back.
     * *Default value = 1*
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     "count": number,
     * }
     * ```
     *
     * Sends CHAT_FEED_READ. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedRead(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Marks all the messages as read in the chat feed.
     * ### JSON param
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends CHAT_FEED_READ_ALL. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedReadAll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Pauses the chat
     * ### JSON param
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends CHAT_FEED_PAUSE. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedPause(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Resumes the chat by scrolling back to bottom
     * ### JSON param
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends CHAT_FEED_UNPAUSE. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedUnpause(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Scroll the chat feed up by the number of pixels specified in the `scrollBy` value.
     * *Default value = 100*
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     "scrollBy":number
     * }
     * ```
     *
     * Sends CHAT_FEED_SCROLL_UP. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedScrollUp(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Scroll the chat feed down by the number of pixels specified in the `scrollBy` value.
     * *Default value = 100*
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     "scrollBy":number
     * }
     * ```
     *
     * Sends CHAT_FEED_SCROLL_DOWN. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedScrollDown(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SCROLL. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedScroll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SCROLL_BOTTOM. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedScrollBottom(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelect(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_ACTION_CANCEL. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectActionCancel(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_ACTION_DELETE. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectActionDelete(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_ACTION_BAN. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectActionBan(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_CHOOSING_ACTION. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectChoosingAction(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_ACTION_PIN. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectActionPin(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_ACTION_HIGHLIGHT. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectActionHighlight(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CHAT_FEED_SELECT_ACTION_SHOUTOUT. Resolves once sent: Twitchat doesn't answer it.
     */
    chatFeedSelectActionShoutout(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CLEAR_CHAT_HIGHLIGHT. Resolves once sent: Twitchat doesn't answer it.
     */
    clearChatHighlight(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends MERGE_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    mergeToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle current poll's visibility
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends POLL_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    pollToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends POLL_CREATE. Resolves once sent: Twitchat doesn't answer it.
     */
    pollCreate(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle current prediction's visibility
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends PREDICTION_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    predictionToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle current bingo's visibility
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends BINGO_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    bingoToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle current raffle's visibility
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends RAFFLE_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    raffleToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle viewer count's visibility
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends VIEWERS_COUNT_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    viewersCountToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle moderation tools' visibility
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends MOD_TOOLS_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    modToolsToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Toggle the censorship of the deleted messages
     * If censorship is enabled, deleted messages content is replaced by `<deleted message>`.
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends CENSOR_DELETED_MESSAGES_TOGGLE. Resolves once sent: Twitchat doesn't answer it.
     */
    censorDeletedMessagesToggle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Request the currently playing spotify track
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends GET_CURRENT_TRACK. Resolves with the data of Twitchat's answer, CURRENT_TRACK; rejects without one in time.
     */
    getCurrentTrack(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Ask of a wheel overlay exists.
     * If it does you'll receive the `WHEEL_OVERLAY_PRESENCE` event.
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends GET_WHEEL_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, WHEEL_OVERLAY_PRESENCE; rejects without one in time.
     */
    getWheelOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_BITSWALL_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, BITSWALL_OVERLAY_PRESENCE; rejects without one in time.
     */
    getBitswallOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_CREDITS_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, CREDITS_OVERLAY_PRESENCE; rejects without one in time.
     */
    getCreditsOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Start a wheel animation.
     * ### JSON param *(optional)*
     * `items` contains the list of wheel items to display on the wheel. There must be between 1 and an infinity of items.
     * `winner` param is the `id` of the entry the wheel should stop to.
     *
     * Data:
     * ```ts
     * {
     *     items:[
     *         {
     *             id:string;
     *             label:string;
     *             data:any;
     *         },
     *         //...
     *     ],
     *     winner:string;
     * }
     * ```
     *
     * Sends WHEEL_OVERLAY_START. Resolves once sent: Twitchat doesn't answer it.
     */
    wheelOverlayStart(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Request current timer / countdown values
     * If it does you'll receive the `TIMER_START` nor `COUNTDOWN_START` event.
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends GET_CURRENT_TIMERS. Resolves with the data of Twitchat's answer, TIMER_START or COUNTDOWN_START; rejects without one in time.
     */
    getCurrentTimers(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Ask if a timer overlay exists.
     * If it does you'll receive the `TIMER_OVERLAY_PRESENCE` event.
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends GET_TIMER_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, TIMER_OVERLAY_PRESENCE; rejects without one in time.
     */
    getTimerOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Starts or stops the emergency mode.
     * If no JSON is given it will simply toggle the current state
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * {
     *     enabled:boolean
     * }
     * ```
     *
     * Sends SET_EMERGENCY_MODE. Resolves once sent: Twitchat doesn't answer it.
     */
    setEmergencyMode(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Ask if a chat highlight overlay exists.
     * If it does you'll receive the `CHAT_HIGHLIGHT_OVERLAY_PRESENCE` event.
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends GET_CHAT_HIGHLIGHT_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, CHAT_HIGHLIGHT_OVERLAY_PRESENCE; rejects without one in time.
     */
    getChatHighlightOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Send a chat message on the "chat highlight" overlay
     * Send no data to hide the current message
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     message: string;//Message with emotes parsed as HTML tags
     *     user:{
     *         id: string;
     *         login: string;
     *         display_name: string;
     *         type: string;
     *         broadcaster_type: string;
     *         description: string;
     *         profile_image_url: string;
     *         offline_image_url: string;
     *         created_at: string;
     *     },
     *     params:{
     *         position:"tl"|"t"|"tr"|"l"|"m"|"r"|"bl"|"b"|"br";
     *     }
     * }
     * ```
     *
     * Sends SET_CHAT_HIGHLIGHT_OVERLAY_MESSAGE. Resolves once sent: Twitchat doesn't answer it.
     */
    setChatHighlightOverlayMessage(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Send a clip to be displayed on the chat highlight overlay
     * ### JSON param
     *
     * Data:
     * ```ts
     * {
     *     //This is the same JSON as the one sent by the Twitch API
     *     clip:{
     *         broadcaster_id: string;
     *         broadcaster_name: string;
     *         created_at: string;
     *         creator_id: string;
     *         creator_name: string;
     *         duration: number;
     *         embed_url: string;
     *         game_id: string;
     *         id: string;
     *         language: string;
     *         thumbnail_url: string;
     *         title: string;
     *         url: string;
     *         video_id: string;
     *         view_count: number;
     *     },
     *     params:{
     *         position:"tl"|"t"|"tr"|"l"|"m"|"r"|"bl"|"b"|"br";
     *     }
     * }
     * ```
     *
     * Sends SHOW_CLIP. Resolves once sent: Twitchat doesn't answer it.
     */
    showClip(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Starts the emergency mode as the user clicked the emergency button
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends START_EMERGENCY. Resolves once sent: Twitchat doesn't answer it.
     */
    startEmergency(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Stop the emergency mode
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends STOP_EMERGENCY. Resolves once sent: Twitchat doesn't answer it.
     */
    stopEmergency(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends a shoutout to the latest raider
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends SHOUTOUT. Resolves once sent: Twitchat doesn't answer it.
     */
    shoutout(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Stops any currently playing text to speech audio
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends STOP_TTS. Resolves once sent: Twitchat doesn't answer it.
     */
    stopTts(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Enabled the speech recognition to control twitchat with your voice
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends ENABLE_STT. Resolves once sent: Twitchat doesn't answer it.
     */
    enableStt(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Disable the speech recognition
     * ### JSON param *(optional)*
     *
     * Data:
     * ```ts
     * -none-
     * ```
     *
     * Sends DISABLE_STT. Resolves once sent: Twitchat doesn't answer it.
     */
    disableStt(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends RAFFLE_START. Resolves once sent: Twitchat doesn't answer it.
     */
    raffleStart(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends RAFFLE_PICK_WINNER. Resolves once sent: Twitchat doesn't answer it.
     */
    rafflePickWinner(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends RAFFLE_END. Resolves once sent: Twitchat doesn't answer it.
     */
    raffleEnd(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends GET_COLS_COUNT. Resolves with the data of Twitchat's answer, SET_COLS_COUNT; rejects without one in time.
     */
    getColsCount(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends COUNTER_GET_ALL. Resolves with the data of Twitchat's answer, COUNTER_LIST; rejects without one in time.
     */
    counterGetAll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends TRIGGERS_GET_ALL. Resolves with the data of Twitchat's answer, TRIGGER_LIST; rejects without one in time.
     */
    triggersGetAll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends EXECUTE_TRIGGER. Resolves once sent: Twitchat doesn't answer it.
     */
    executeTrigger(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends TOGGLE_TRIGGER. Resolves once sent: Twitchat doesn't answer it.
     */
    toggleTrigger(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends SEND_MESSAGE. Resolves once sent: Twitchat doesn't answer it.
     */
    sendMessage(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends COUNTER_GET. Resolves with the data of Twitchat's answer, COUNTER_UPDATE; rejects without one in time.
     */
    counterGet(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends COUNTER_ADD. Resolves once sent: Twitchat doesn't answer it.
     */
    counterAdd(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends TIMER_ADD. Resolves once sent: Twitchat doesn't answer it.
     */
    timerAdd(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends COUNTDOWN_ADD. Resolves once sent: Twitchat doesn't answer it.
     */
    countdownAdd(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CREATE_POLL. Resolves once sent: Twitchat doesn't answer it.
     */
    createPoll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends STOP_POLL. Resolves once sent: Twitchat doesn't answer it.
     */
    stopPoll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CREATE_PREDICTION. Resolves once sent: Twitchat doesn't answer it.
     */
    createPrediction(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends STOP_PREDICTION. Resolves once sent: Twitchat doesn't answer it.
     */
    stopPrediction(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends CREATE_RAFFLE. Resolves once sent: Twitchat doesn't answer it.
     */
    createRaffle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends STOP_RAFFLE. Resolves once sent: Twitchat doesn't answer it.
     */
    stopRaffle(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends GET_SUMMARY_DATA. Resolves with the data of Twitchat's answer, SUMMARY_DATA; rejects without one in time.
     */
    getSummaryData(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_AD_BREAK_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, AD_BREAK_OVERLAY_PRESENCE; rejects without one in time.
     */
    getAdBreakOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_AD_BREAK_OVERLAY_PARAMETERS. Resolves with the data of Twitchat's answer, AD_BREAK_OVERLAY_PARAMETERS; rejects without one in time.
     */
    getAdBreakOverlayParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_DISTORT_OVERLAY_PARAMETERS. Resolves with the data of Twitchat's answer, DISTORT_OVERLAY_PARAMETERS; rejects without one in time.
     */
    getDistortOverlayParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_BITS_WALL_OVERLAY_PARAMETERS. Resolves with the data of Twitchat's answer, BITSWALL_OVERLAY_PARAMETERS; rejects without one in time.
     */
    getBitsWallOverlayParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Send chat notifications only visible by you on Twitchat.
     * The `icon` props can have one of those values:
     *
     * Data:
     * ```ts
     * ad add alert animate announcement anon api automod badge ban bingo bits block boost bot broadcast broadcaster change channelPoints chatCommand chatPoll checkmark clearChat click clip coffee coin color commands conversation copy count countdown credits cross date debug delete dice discord donor download dragZone easing edit elevated elgato emergency emote enter filters firstTime fix follow follow_outline font fontSize fullscreen gift github goxlr goxlr_bleep goxlr_fx hand heat help hide highlight history hypeChat idea info internet kofi leave list live loader lock loop magnet markRead max merge microphone microphone_mute microphone_recording min minus mod move music mute newtab next noMusic notification number obs offline online orderable overlay params partner patreon pause paypal pin pipette placeholder play poll polygon prediction premium presentation press prev prime pros qna raid read refresh reply returning reward_highlight rightClick rotate save scale scroll scrollDown scrollUp search shadow shield shieldMode shoutout show skip slow spotify stars stop sub test thickness ticket tiktok timeout timer train train_boost translate trash tts twitch twitchat twitter ulule unban unblock unfollow unlock unmod unmute unpin unvip update upload url user vibrate vip voice voicemod volume watchStreak whispers youtube
     * ```
     *
     * Sends CUSTOM_CHAT_MESSAGE. Resolves once sent: Twitchat doesn't answer it.
     */
    customChatMessage(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends GET_PREDICTIONS_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, PREDICTIONS_OVERLAY_PRESENCE; rejects without one in time.
     */
    getPredictionsOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_PREDICTIONS_OVERLAY_PARAMETERS. Resolves with the data of Twitchat's answer, PREDICTIONS_OVERLAY_PARAMETERS; rejects without one in time.
     */
    getPredictionsOverlayParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_POLLS_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, POLLS_OVERLAY_PRESENCE; rejects without one in time.
     */
    getPollsOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_CHAT_POLL_OVERLAY_PRESENCE. Resolves with the data of Twitchat's answer, CHAT_POLL_OVERLAY_PRESENCE; rejects without one in time.
     */
    getChatPollOverlayPresence(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_POLLS_OVERLAY_PARAMETERS. Resolves with the data of Twitchat's answer, POLLS_OVERLAY_PARAMETERS; rejects without one in time.
     */
    getPollsOverlayParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_CHAT_POLL_OVERLAY_PARAMETERS. Resolves with the data of Twitchat's answer, CHAT_POLL_OVERLAY_PARAMETERS; rejects without one in time.
     */
    getChatPollOverlayParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_BINGO_GRID_PARAMETERS. Resolves with the data of Twitchat's answer, BINGO_GRID_PARAMETERS; rejects without one in time.
     */
    getBingoGridParameters(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_LABEL_OVERLAY_PARAMS. Resolves with the data of Twitchat's answer, LABEL_OVERLAY_PARAMS; rejects without one in time.
     */
    getLabelOverlayParams(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends GET_LABEL_OVERLAY_PLACEHOLDERS. Resolves with the data of Twitchat's answer, LABEL_OVERLAY_PLACEHOLDERS; rejects without one in time.
     */
    getLabelOverlayPlaceholders(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends AUTOMOD_ACCEPT. Resolves once sent: Twitchat doesn't answer it.
     */
    automodAccept(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends AUTOMOD_REJECT. Resolves once sent: Twitchat doesn't answer it.
     */
    automodReject(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends GET_DONATION_GOALS_OVERLAY_PARAMS. Resolves with the data of Twitchat's answer, DONATION_GOALS_OVERLAY_PARAMS; rejects without one in time.
     */
    getDonationGoalsOverlayParams(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends QNA_HIGHLIGHT. Resolves once sent: Twitchat doesn't answer it.
     */
    qnaHighlight(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends QNA_SKIP. Resolves once sent: Twitchat doesn't answer it.
     */
    qnaSkip(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends QNA_SESSION_GET_ALL. Resolves with the data of Twitchat's answer, QNA_SESSION_LIST; rejects without one in time.
     */
    qnaSessionGetAll(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends HIDE_ALERT. Resolves once sent: Twitchat doesn't answer it.
     */
    hideAlert(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends GET_ANIMATED_TEXT_CONFIGS. Resolves with the data of Twitchat's answer, ANIMATED_TEXT_CONFIGS; rejects without one in time.
     */
    getAnimatedTextConfigs(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends ANIMATED_TEXT_SET. Resolves once sent: Twitchat doesn't answer it.
     */
    animatedTextSet(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends ANIMATED_TEXT_CLOSE. Resolves once sent: Twitchat doesn't answer it.
     */
    animatedTextClose(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
    /**
     * Sends GET_CUSTOM_TRAIN_STATE. Resolves with the data of Twitchat's answer, CUSTOM_TRAIN_STATE; rejects without one in time.
     */
    getCustomTrainState(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any>>;
    /**
     * Sends PLAY_SFXR. Resolves once sent: Twitchat doesn't answer it.
     */
    playSfxr(data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<void>;
}

declare class TwitchatError extends Error {
    name: "TwitchatError";
    /** "UNKNOWN_ACTION", "NOT_CONNECTED" or "TIMEOUT". */
    code: "UNKNOWN_ACTION" | "NOT_CONNECTED" | "TIMEOUT";
    action: string | null;
    /** The closest known action, when this one was unknown. */
    suggestion: string | null;
}

/** catapult-common's TwitchatAction. */
interface TwitchatNotificationAction {
    label: string;
    actionType: string;
    url?: string | null;
    message?: string | null;
    theme?: string | null;
}

/** catapult-common's TwitchatNotification. */
interface TwitchatNotification {
    /** Shared by every client relaying it, so only one of them does. */
    id: string;
    message: string;
    style?: string | null;
    icon?: string | null;
    authorName?: string | null;
    actions?: TwitchatNotificationAction[] | null;
}

interface CatapultTwitchatApi {
    /** Every action Twitchat accepts. */
    readonly ACTIONS: readonly TwitchatActionType[];
    /** Every event Twitchat sends. */
    readonly EVENTS: readonly TwitchatEventType[];
    /** The event(s) answering each "get" action. */
    readonly REPLIES: Readonly<Partial<Record<TwitchatActionType, readonly TwitchatEventType[]>>>;
    readonly TwitchatError: typeof TwitchatError;

    /** One shortcut per action: actions.chatFeedPause() is send("CHAT_FEED_PAUSE"). */
    readonly actions: TwitchatActions;

    /** Whether Twitchat can be reached, i.e. the page is connected to OBS. */
    isConnected(): boolean;
    /** Sends an action; for a "get" one, resolves with the data of Twitchat's answer. */
    send(action: TwitchatActionType, data?: Record<string, any>, options?: TwitchatRequestOptions): Promise<Record<string, any> | void>;
    /** Subscribes to an event (or action sent by another client), "*" for all of them; returns the unsubscribe function. */
    on<T extends TwitchatEventType>(type: T, handler: (data: TwitchatEventMap[T], envelope: TwitchatEnvelope) => void): () => void;
    on(type: TwitchatActionType | "*", handler: (data: Record<string, any>, envelope: TwitchatEnvelope) => void): () => void;
    off(type: TwitchatEventType | TwitchatActionType | "*", handler: (...args: any[]) => void): void;
    /** Resolves with the data of the next such event. */
    once<T extends TwitchatEventType>(type: T): Promise<TwitchatEventMap[T]>;
    /** Sends a Catapult notification to Twitchat's chat, once across every connected client. */
    relay(notification: TwitchatNotification): Promise<boolean>;
}

/** Fired on document. */
interface DocumentEventMap {
    /** A notification for twitchat.js to relay. */
    "catapult:twitchat:notify": CustomEvent<TwitchatNotification>;
}

declare var CatapultTwitchat: CatapultTwitchatApi;
