INSERT INTO tw_definition (id, label, description, sort_order) VALUES
  ('violence_graphic',   'Violence (graphic)',          'Blood, gore, explicit injuries, on-screen death.',     1),
  ('sexual_content',     'Sexual content',              'Nudity, sexual situations, suggestive themes.',        2),
  ('sexual_assault',     'Sexual assault',              'Rape, attempted rape, sexual coercion.',               3),
  ('suicide',            'Suicide / self-harm',         'Suicide attempts, self-harm depictions or themes.',    4),
  ('death_of_animal',    'Death of animal',             'Pets or wildlife killed on screen.',                   5),
  ('death_of_child',     'Death of child',              'Children harmed or killed.',                           6),
  ('flashing_lights',    'Flashing lights',             'Strobe, rapid flashes (photosensitivity).',            7),
  ('loud_noises',        'Loud noises',                 'Sudden loud sounds, explosions.',                      8),
  ('drugs_alcohol',      'Drugs / alcohol',             'Drug use, alcohol abuse, addiction.',                  9),
  ('gambling',           'Gambling',                    'Casino mechanics, betting, loot boxes.',              10),
  ('profanity',          'Strong language / profanity', 'Frequent or strong swearing.',                        11),
  ('discrimination',     'Discrimination / hate',       'Racism, homophobia, hate speech.',                    12),
  ('horror_jumpscare',   'Horror / jump scares',        'Sudden frights, horror imagery.',                     13),
  ('medical_blood',      'Medical procedures / blood',  'Surgery, needles, medical gore.',                     14),
  ('spiders_insects',    'Spiders / insects',           'Arachnophobia, entomophobia triggers.',               15),
  ('emotional_distress', 'Emotional distress',          'Heavy grief, despair, trauma themes.',                16),
  ('domestic_violence',  'Domestic violence',           'Violence within home/family.',                        17),
  ('abandonment',        'Abandonment',                 'Themes of being left alone, isolation.',              18),
  ('food_disorder',      'Food disorders',              'Eating disorders, body image distress.',              19),
  ('vomit',              'Vomit',                       'Vomiting depictions.',                                20);

INSERT INTO tw_steam_keyword (tw_id, keyword) VALUES
  ('violence_graphic', 'blood'),
  ('violence_graphic', 'gore'),
  ('violence_graphic', 'violence'),
  ('violence_graphic', 'violent'),
  ('violence_graphic', 'killing'),
  ('violence_graphic', 'combat'),
  ('violence_graphic', 'injury'),
  ('sexual_content',   'nudity'),
  ('sexual_content',   'sexual'),
  ('sexual_content',   'sex'),
  ('sexual_content',   'suggestive'),
  ('sexual_content',   'erotic'),
  ('drugs_alcohol',    'drug'),
  ('drugs_alcohol',    'alcohol'),
  ('drugs_alcohol',    'tobacco'),
  ('drugs_alcohol',    'substance'),
  ('drugs_alcohol',    'intoxication'),
  ('gambling',         'gambling'),
  ('gambling',         'betting'),
  ('profanity',        'profanity'),
  ('profanity',        'crude'),
  ('profanity',        'strong language'),
  ('profanity',        'vulgarity');

INSERT INTO tw_steam_content_id_mapping (tw_id, steam_content_id) VALUES
  ('sexual_content',   1),
  ('violence_graphic', 2),
  ('sexual_content',   3),
  ('sexual_content',   4);
